public: true
type: "docs"
category: "collection development and management"
tags:
  - "workflow"
title: "Aurora User Guide"
description: "User documentation for the Aurora digital records transfer application."
pages:
  - ["Aurora User Guide", "index"]
